from .prompt_chain import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .syntax_test import NODE_CLASS_MAPPINGS as SYNTAX_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SYNTAX_DISPLAY_MAPPINGS
import os

# Merge mappings
NODE_CLASS_MAPPINGS.update(SYNTAX_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SYNTAX_DISPLAY_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
